# Generated by Django 4.1.3 on 2024-04-16 08:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychometric', '0011_alter_studytips_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careeridea',
            name='idea',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choiceidea',
            name='idea',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studytips',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
